### ISSUE TITLE
always show precomputed output

### ISSUE THREAD

**Issue by pelikhan** [microsoft/z3guide#28]
It would be more efficient to immediately show the pre-computed output (that's one less button and it's useful information). We have it let's show it.

I recommend doing this in remark at rendering time by generating a new code node; that later gets rendered by docusaurus. As a bonus, it should be the copy/wrap icons.

Also, drop "Output:", it feels more like noise at this point.

**Comment by rlisahuang** [comment]
So were you suggesting that instead of having an explicit button to toggle the output, we always show it below the code snippet (and potentially polish the component to distinguish it from the regular code blocks)?

**Comment by pelikhan** [comment]
Yes. The current color sheme is good enough IMO.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by NikolajBjorner** [comment]
I have to say I got accustomed to the current scheme. It reveals information on demand and eases the flow with consecutive examples.
If the plan is to make the examples editable, then on-demand reveal would be used anyhow.

**Comment by rlisahuang** [comment]
I also prefer on-demand reveal. It keep things clean (there are really long outputs for some snippets). When it comes to editable snippets, there needs to be a separate button that says "execute," so that the current button still shows/hides any output message, while the "execute" button sends a request for interpreting smtlib2.
