### ISSUE TITLE
Cross references

### ISSUE THREAD

**Issue by NikolajBjorner** [microsoft/z3guide#41]
Develop schema for cross referencing material from the tutorial.
So far there is a way to cross reference SMTLIB in some format. For example.

> SMTLIB2 standard [Integers](http://smtlib.cs.uiowa.edu/theories-Ints.shtml)

Other categories of cross references are:

- Reference manual
- Lectures
- Papers
- Case Studies
- Stackoverflow questions / github discussions - in a nutshell user interaction. 

What is a good schema for the static content and way to integrate dynamic content?
Preliminary way:

>[!NOTE]
>Information the user should notice even if skimming.

[!TIP]
Optional information to help a user be more successful.

[!IMPORTANT]
Essential information required for user success.

[!CAUTION]
Negative potential consequences of an action.

[!WARNING]
Dangerous certain consequences of an action.

The last point about cross-referencing user interaction is more ambitious and should be aligned with developing methods to integrate learning feedback. Given the state of z3guide, what is the long- and short-term plan for integrating such signals?
What are the technical enablers? (let me zoogl3 this, or link to github discussions, create discussions, cross-link discussions?)

**Comment by pelikhan** [comment]
See also https://github.com/orgs/github-community/discussions/16925

**Comment by ayanamonr** [comment]
a quick survey of the cross references: 
- *info* for important reference information like a textbook
- *tip* for general usage hints, not cross references 
- *note* for things like a definition of a concept and why it is important to understand, can include a link to a source that describes in more detail 
- *caution* for typical errors that come from working with the concept in question 
- at the bottom of each page we can have a banner that links to the z3 documentation referenced in this section

Instead of using an alert to integrate github discussions and stackoverflow, it may be more valuable to include links to those discussions near the physical run button of each code snippet
> Motivating example: you're testing code and working through the examples on the arrays page. You get an unexpected error.
>So you: 1. click on ghdiscussions or stackoverflow. 2. Ideally the content you edited is autopopulated and you can essentially ask why it isn't working. 3. or instead of autopopulating, we provide the original code, the edited code, and the link to a start a new discussion or stack overflow post?

@pelikhan I'm thinking that this question launches a larger one: should we put together a style guide so that the design decisions for rise4fun are consistent for whoever is working on it z3, other languages, etc. ?

**Comment by NikolajBjorner** [comment]
OK, there are two points:
- design how to cross reference static material (at bottom of page).
- design how to integrate dynamic content, discussions; already existing, or not yet existing (but could be added to github discussions).
