### ISSUE TITLE
Run Z3 in the browser

### ISSUE THREAD

**Issue by rlisahuang** [microsoft/z3guide#43]
Attempting to run Z3 in the browser (currently without webworkers). Code in #42 .

According to @NikolajBjorner it seems that there have been major changes to the JS API since June 14, which involves the names of several files (e.g. `wrapper.js` was gone) and the signature of `init` (it used to accept one argument, which is the result of `initZ3`, now none).

@bakkot It would be super helpful if you could provide us with some examples of:
- Running Z3 in the browser without webworkers, and
- ... using webworkers

with the current (4.9.1) npm release.

**Comment by bakkot** [comment]
Sure, I can try to put together a small example.

> Running Z3 in the browser without webworkers

That's not going to be a thing. Z3 does not work correctly without threads, and using threads means using webworkers.

**Comment by bakkot** [comment]
Here's a working example: https://github.com/bakkot/z3-web-demo

It should be completely reproducible. It's hosted at https://bakkot.github.io/z3-web-demo/.

**Comment by rlisahuang** [comment]
Thanks @bakkot ! This is really helpful. 

Re: webworkers,I am aware that multiple instances of `z3-built.js` will be fired for long-running operations (through multiple webworkers I suppose). We would like to set timeout for all z3 executions through the web and report the status of operation accordingly to the user (e.g. "taking a while...", "output unavailable due to the timeout limit"). 

My understanding is that (a) there is no timeout for such operations at the moment in the JS bindings, and (b) we cannot configure a timeout through the API, let alone obtaining the status of operation from the webworkers. 

A potential solution is to use our own webworkers so that we can configure timeouts for termination as well as communication for the status of operation. In that case, is it possible to do something like

```js
const worker = new Worker('worker.js');
worker.postMessage(z3_input);

worker.onMessage((e) => {
   showMsg(e.data);
});

setTimeout(() => {
  worker.terminate();
}, 3*60*1000); // terminate after 3 minutes
```

where `worker.js` handles communication with z3 (maybe `z3-built.js`?), such that only *one* `z3-built.js` instance is fired for every request for execution?

**Comment by bakkot** [comment]
Emscripten, which is the tool used to compile Z3 for the web, is not set up to allow you to manage workers yourself.

Emscripten _does_ expose a mechanism to kill all outstanding workers, which is `em.PThread.terminateAllThreads()`. I don't know how well z3 would take to having a thread killed while something like `Z3_eval_smtlib2_string` is executing on that thread, though; it's possible that would leave things in a bad state. A question for @NikolajBjorner, probably. (I know there's `Z3_interrupt` but I don't think it will work in emscripten.)

Also, other parts of the internals aren't currently set up for this - there's a lock which will prevent you from running multiple async operations at once, and there's no way to manually release that lock as-is, which means that if you call `terminateAllThreads` while an async operation is running you will never be able to run another one. If y'all think that killing threads is the way to go I can write a patch which will let you release that lock so that part works, at least.

**Comment by rlisahuang** [comment]
@pelikhan Sorry to bother you on your vacation, but it'll be nice to have your input on the timeout issue

**Comment by rlisahuang** [comment]
@bakkot We use webpack 5 for bundling so your solution in the demo doesn't work. It seems that webpack and emscripten-generated WASM don't work really well. I have been trying to follow the example in [this repo](https://github.com/9oelM/emscripten-cplusplus-webpack-example) which looks very similar to our scenario. Is it possible to bundle z3-solver using webpack in a similar way?
